networks:
  My-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: netflix-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - My-network

  web-server:
    build:
      context: .
      dockerfile: Dockerfile.web-server
    restart: always
    entrypoint: ["node", "app.js"]
    ports:
      - "3000:3000"
    container_name: web-server
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ntfx
      - RECOMMENDATION_SERVER_HOST=recommendation-server
      - RECOMMENDATION_SERVER_PORT=8080
    stdin_open: true  # Keep stdin open for interactive use
    networks:
      - My-network
  
  recommendation-server:
    build:
      context: .
      dockerfile: Dockerfile.recommendation-server
    entrypoint: ["./server"]
    ports:
      - "8080:8080"
    container_name: recommendation-server
    stdin_open: true  # Keep stdin open for interactive use
    tty: true  # Allocate a TTY for interactive use
    init: true 
    networks:
      - My-network

  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   container_name: netflix-client
  #   stdin_open: true  # Keep stdin open for interactive use
  #   tty: true  # Allocate a TTY for interactive use
  #   networks:
  #     - My-network

volumes:
  mongodb_data: