# Use Node.js image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the server will run on
EXPOSE 3000

# Set environment variables
ENV MONGO_URI=mongodb://mongo:27017/ntfx 
ENV RECOMMENDATION_SERVER_HOST=recommendation-server
ENV RECOMMENDATION_SERVER_PORT=8080

# Run the server
CMD ["node", "app.js"]