networks:
  My-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: netflix-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - My-network

  web-server:
    build:
      context: .
      dockerfile: Dockerfile.web-server
    ports:
      - "3000:3000"
    container_name: web-server
    environment:
      MONGO_URI: mongodb://mongodb:27017/ntfx
      RECOMMENDATION_SERVER_HOST: recommendation-server
      RECOMMENDATION_SERVER_PORT: 8080
      PORT: 3000
      CONNECTION_STRING: mongodb://mongodb:27017
    networks:
      - My-network
    depends_on:
      - recommendation-server

  recommendation-server:
    build:
      context: .
      dockerfile: Dockerfile.recommendation-server
    ports:
      - "8080:8080"
    container_name: recommendation-server
    environment:
     PORT: 8080
    networks:
      - My-network
      
volumes:
  mongodb_data: