### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "jane_doe",
  "password": "securePassword123",
  "email": "jane.doe@example.com",
  "picture": "https://example.com/jane.jpg"
}

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "jane_doa",
  "password": "securePassword124",
  "email": "jane.doa@example.com",
  "picture": "https://example.com/jane.jpg"
}

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "jane_dol",
  "password": "securePassword222",
  "email": "jane.dol@example.com",
  "picture": "https://example.com/jane.jpg"
}

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "jane_don",
  "password": "securePassword246",
  "email": "jane.don@example.com",
  "picture": "https://example.com/jane.jpg"
}

### Get user details by ID
GET http://localhost:3000/api/users/677eb0296b8d36d5eacf6b53
