#I use exstension "REST client"

### POST Request to create a category
POST http://localhost:3000/api/categories
Content-Type: application/json
X-User-Id: 12345 

{
  "name": "Drama",
  "promoted": true,
  "movieIds": "101 102 104"
}

### POST Request to create a category
POST http://localhost:3000/api/categories
Content-Type: application/json
X-User-Id: 677a322df8ecf2fbed1be3eb

{
  "name": "Drama",
  "promoted": true,
  "movieIds": "104 101 105"
}

### GET Request to fetch all categories
GET http://localhost:3000/api/categories
X-User-Id: 12345

### GET Request to fetch all categories for non-admin user
GET http://localhost:3000/api/categories


### POST Request to create a category
POST http://localhost:3000/api/categories
Content-Type: application/json
X-User-Id: 12345

{
  "name": "Action",
  "promoted": true,
  "movieIds": "100"
}

### PATCH Request to update a category by ID
PATCH http://localhost:3000/api/categories/6773e417b04c345a8ff87c88
Content-Type: application/json
X-User-Id: 12345

{
  "name": "Action & Adventure",
  "promoted": false,
  "movieIds": "100 101 102 103"
}

### PATCH Request to update a category by ID
PATCH http://localhost:3000/api/categories/6773e40cb04c345a8ff87c82
Content-Type: application/json
X-User-Id: 12345

{
  "movieIds": "67780527088182814110c6bc"
}

### GET Request to fetch a category by ID
GET http://localhost:3000/api/categories/6773e1b9160f9deee8143eb2
X-User-Id: 12345

### GET Request to incorrect category ID
GET http://localhost:3000/api/categories/676fd82a8aa151542d45bc97
X-User-Id: 12345

### GET Request to incorrect user ID
GET http://localhost:3000/api/categories/676fd82a8aa151542d45bc96
X-User-Id: 12346


### GET Request to incorrect category ID
GET http://localhost:3000/api/categories/foo
X-User-Id: 12345

### DELETE Request to delete a category by ID
DELETE http://localhost:3000/api/categories/6773e1a4160f9deee8143ea9
X-User-Id: 12345
