### POST Request to create a new movie
POST http://localhost:3000/api/movies
Content-Type: application/json
X-User-Id: 12345

{
  "name": "Inception",
  "categoryIds": "123 456"
}

### POST Request to create another new movie
POST http://localhost:3000/api/movies
Content-Type: application/json
X-User-Id: 12345

{
  "name": "Interstellar",
  "categoryIds": "123 789"
}

### POST Request to create a new movie
POST http://localhost:3000/api/movies
Content-Type: application/json
X-User-Id: 12345

{
  "name": "Frozen 2",
  "categoryIds": "123 456"
}

### GET Request to fetch all movies
GET http://localhost:3000/api/movies
X-User-Id: 677a3535ff2c327b25afe4c9

### GET Request to fetch a specific movie by ID
GET http://localhost:3000/api/movies/677a2f5bae01f686add8fc7d
X-User-Id: 12345

### PUT Request to update a specific movie by ID
PUT http://localhost:3000/api/movies/677a65a0039ba77bc1d2e7e3
Content-Type: application/json
X-User-Id: 677a3535ff2c327b25afe4c9

{
    "name": "Inception",
    "categoryIds": "677a360158388258ff806cd7"
}

### DELETE Request to delete a specific movie by ID
DELETE http://localhost:3000/api/movies/677d9a645da55b21f8e8a8fd
X-User-Id: 677be4eeeed43edec74518c9

### GET Request to search movies by query
GET http://localhost:3000/api/movies/search/Frozen

### GET Request to search movies by another query
GET http://localhost:3000/api/movies/search/123

### GET Request to search movies by query
GET http://localhost:3000/api/movies/search/Inception

### GET Request to search movies by another query
GET http://localhost:3000/api/movies/search/In

### GET Request to fetch movies by categories
GET http://localhost:3000/api/movies
X-User-Id: 12345

### GET Request to fetch movies by categories
GET http://localhost:3000/api/movies/677a2f5bae01f686add8fc7d/recommend
X-User-Id: 12345

### POST Request to CPP server
POST http://localhost:3000/api/movies/677b7f2255b36ed6b4e23529/recommend
Content-Type: application/json
X-User-Id: 677a414d627a30004f380913


### POST Request to CPP server
POST http://localhost:3000/api/movies/677b7f2255b36ed6b4e23529/recommend
Content-Type: application/json
X-User-Id: 677bbd4454ceb57c5084b0d5


### POST Request to CPP server
POST http://localhost:3000/api/movies/677b97a8f2aae6e494dacaf0/recommend
Content-Type: application/json
X-User-Id: 677bbd4454ceb57c5084b0d5

### GET Request to CPP server
GET http://localhost:3000/api/movies/677d91a598702e692043f361/recommend
Content-Type: application/json
X-User-Id: 677d936c6d6d9e1c2a9fa743


### GET Request to CPP server
POST  http://localhost:3000/api/movies/677d92f56d6d9e1c2a9fa737/recommend
Content-Type: application/json
X-User-Id: 677d936c6d6d9e1c2a9fa743

### GET Request to CPP server
POST http://localhost:3000/api/movies/677d91a598702e692043f361/recommend
Content-Type: application/json
X-User-Id: 677d9477cb5eaf9fcf337a78